### ISSUE TITLE
Fails to set version on a brand new project with no VER tags ever in the project.

### ISSUE THREAD

**Issue by daborg69** [SlugEnt/SlugCI#11]
********************************** ERROR ****************************************
-->(Error):  ArgumentException: Unable to find the . or - in the prerelease portion of the semanticVersion []
********************************** ERROR ****************************************

   at Slug.CI.SemVersionPreRelease..ctor(String preReleaseTag) in C:\A_Dev\SlugEnt\SlugCI\src\SlugCI\SemVersionPreRelease.cs:line 69
   at Slug.CI.Program.ManualVersionPrompts(CISession ciSession, SlugCI slugCi) in C:\A_Dev\SlugEnt\SlugCI\src\SlugCI\Program.cs:line 398
   at Slug.CI.Program.Menu(CISession ciSession, SlugCI slugCi) in C:\A_Dev\SlugEnt\SlugCI\src\SlugCI\Program.cs:line 318
   at Slug.CI.Program.Main(String rootdir, String deployto, String compileconfig, Boolean faststart, String verbosity, Boolean interactive, Boolean skipnuget, Boolean failedtestsok, Boolean info, Boolean setup, Boolean skipangular, Boolean skiptests) in C:\A_Dev\SlugEnt\SlugCI\src\SlugCI\Program.cs:line 152

**Comment by daborg69** [comment]
This is resolved in upcoming Ver0.33.0
